export TERM=xterm-256color
export COLORTERM=truecolor
export PATH="$HOME/bin:$PATH"

if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
    tmux attach || tmux new-session
fi

eval "$(starship init bash)"

